### ISSUE TITLE
quick-start error

### ISSUE THREAD

**Issue by hofmockel-zz** [pacifica/pacifica-userinterface-project#1]
$ composer quick-start
> composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> DrupalComposer\DrupalScaffold\Plugin::scaffold
  - .csslintrc (https://git.drupalcode.org/project/drupal/raw/8.7.3/.csslintrc): Downloading (100%)         
  - .editorconfig (https://git.drupalcode.org/project/drupal/raw/8.7.3/.editorconfig): Downloading (100%)         
  - .eslintignore (https://git.drupalcode.org/project/drupal/raw/8.7.3/.eslintignore): Downloading (100%)         
  - .eslintrc.json (https://git.drupalcode.org/project/drupal/raw/8.7.3/.eslintrc.json): Downloading (100%)         
  - .gitattributes (https://git.drupalcode.org/project/drupal/raw/8.7.3/.gitattributes): Downloading (100%)         
  - .ht.router.php (https://git.drupalcode.org/project/drupal/raw/8.7.3/.ht.router.php): Downloading (100%)         
  - .htaccess (https://git.drupalcode.org/project/drupal/raw/8.7.3/.htaccess): Downloading (100%)         
  - index.php (https://git.drupalcode.org/project/drupal/raw/8.7.3/index.php): Downloading (100%)         
  - robots.txt (https://git.drupalcode.org/project/drupal/raw/8.7.3/robots.txt): Downloading (100%)         
  - sites/default/default.services.yml (https://git.drupalcode.org/project/drupal/raw/8.7.3/sites/default/default.services.yml): Downloading (100%)         
  - sites/default/default.settings.php (https://git.drupalcode.org/project/drupal/raw/8.7.3/sites/default/default.settings.php): Downloading (100%)         
  - sites/development.services.yml (https://git.drupalcode.org/project/drupal/raw/8.7.3/sites/development.services.yml): Downloading (100%)         
  - sites/example.settings.local.php (https://git.drupalcode.org/project/drupal/raw/8.7.3/sites/example.settings.local.php): Downloading (100%)         
  - sites/example.sites.php (https://git.drupalcode.org/project/drupal/raw/8.7.3/sites/example.sites.php): Downloading (100%)         
  - update.php (https://git.drupalcode.org/project/drupal/raw/8.7.3/update.php): Downloading (100%)         
  - web.config (https://git.drupalcode.org/project/drupal/raw/8.7.3/web.config): Downloading (100%)         
> php docroot/core/scripts/drupal quick-start pacifica --no-interaction
 0/19 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
Installing Drupal

 1/19 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]
Choose profile

 2/19 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]
Choose profile

 3/19 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]
Verify requirements

 4/19 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]
Set up database

 5/19 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]
Set up database

 6/19 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]
Set up database

 7/19 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]
Set up database

 8/19 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]
Set up database

 9/19 [▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░]
Install site

In RouteProvider.php line 201:
                                        
  Route "openapi.docs" does not exist.  
                                        

quick-start [--langcode [LANGCODE]] [--site-name [SITE-NAME]] [--host [HOST]] [--port [PORT]] [-s|--suppress-login] [--] [<install-profile>]

Script php docroot/core/scripts/drupal quick-start pacifica --no-interaction handling the quick-start event returned with error code 1

**Comment by hofmockel-zz** [comment]
I was able to use the Drupal Install from the UI and select the Pacifica install profile.

I got this error during the "install site" routine:

> An AJAX HTTP error occurred.
> HTTP Result Code: 200
> Debugging information follows.
> Path: /core/install.php?rewrite=ok&langcode=en&profile=pacifica&id=1&op=do_nojs&op=do
> StatusText: OK
> ResponseText: Symfony\Component\Routing\Exception\RouteNotFoundException: Route "openapi.docs" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 201 of /Users/hofm963/Sites/pacifica-interface/docroot/core/lib/Drupal/Core/Routing/RouteProvider.php).

However, it was not a fatal error and a reload of the page progressed me forward to a site configuration page. And the install was completed.

However, it did not have any theme installed. I chose Bartik but it looks like the Pacifica Logo was pushed into Bartik and is WAY too large.

<img width="1291" alt="Screen Shot 2019-06-18 at 11 47 23 AM" src="https://user-images.githubusercontent.com/3505110/59711004-0b8bc080-91bf-11e9-9087-2026c7bb638e.png">

**Comment by dmlb2000** [comment]
The image size does need to be addressed, I've got a bug reference to https://www.drupal.org/project/lightning/issues/3062585 to figure out what's up with the missnig route to `openapi.docs`

**Comment by dmlb2000** [comment]
https://github.com/acquia/lightning/pull/654 seems like a minor update to the lightning_api is the solution. This needs to happen in the parent profile of the subprofile.

**Comment by hofmockel-zz** [comment]
I've been trying to reproduce the error and CANNOT. It is building fine right now, however it does land without any theme.

* But why are you doing a QuickStart? It doesn't really install Drupal. Wouldn't this be more permanently done with Drush site-install https://drushcommands.com/drush-8x/core/site-install/

Assuming Drush is installed or Installing Drush doesn't seem out of line here.

**Comment by dmlb2000** [comment]
No, drush 9.0 is part of the install profile, `./vendor/bin/drush` should be there for doing a site install.

The thought is that `drush` really depends on an infrastructure to be there to point at. We'd need some standard development environment that's a bit more than `quick-start`.

**Comment by dmlb2000** [comment]
@hofmockel So the theme is all gone? that does sound like the install only went half way.
